apiVersion: runpod.crossplane.io/v1alpha1
kind: ClusterProviderConfig
metadata:
  name: restricted-management
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: runpod-credentials
      name: runpod-management
      key: apiKey
