apiVersion: runpod.crossplane.io/v1alpha1
kind: ProviderConfig
metadata:
  name: restricted-management
  namespace: runpod-system
spec:
  credentials:
    source: Secret
    secretRef:
      namespace: runpod-system
      name: runpod-management
      key: apiKey
