//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2025 The Crossplane Authors <https://crossplane.io>
//
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	"github.com/crossplane/crossplane/apis/v2/core/v2"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheck) DeepCopyInto(out *EndpointCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheck.
func (in *EndpointCheck) DeepCopy() *EndpointCheck {
	if in == nil {
		return nil
	}
	out := new(EndpointCheck)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheckList) DeepCopyInto(out *EndpointCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]EndpointCheck, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheckList.
func (in *EndpointCheckList) DeepCopy() *EndpointCheckList {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *EndpointCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheckObservation) DeepCopyInto(out *EndpointCheckObservation) {
	*out = *in
	in.LastCheckedAt.DeepCopyInto(&out.LastCheckedAt)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheckObservation.
func (in *EndpointCheckObservation) DeepCopy() *EndpointCheckObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckObservation)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheckParameters) DeepCopyInto(out *EndpointCheckParameters) {
	*out = *in
	if in.EndpointIDRef != nil {
		in, out := &in.EndpointIDRef, &out.EndpointIDRef
		*out = new(v2.Reference)
		(*in).DeepCopyInto(*out)
	}
	out.InferenceCredentialsSecretRef = in.InferenceCredentialsSecretRef
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheckParameters.
func (in *EndpointCheckParameters) DeepCopy() *EndpointCheckParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckParameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheckSpec) DeepCopyInto(out *EndpointCheckSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheckSpec.
func (in *EndpointCheckSpec) DeepCopy() *EndpointCheckSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *EndpointCheckStatus) DeepCopyInto(out *EndpointCheckStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new EndpointCheckStatus.
func (in *EndpointCheckStatus) DeepCopy() *EndpointCheckStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckStatus)
	in.DeepCopyInto(out)
	return out
}
