//go:build !ignore_autogenerated

// SPDX-FileCopyrightText: 2026 The provider-runpod Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import runtime "k8s.io/apimachinery/pkg/runtime"

func (in *EndpointCheck) DeepCopyInto(out *EndpointCheck) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}
func (in *EndpointCheck) DeepCopy() *EndpointCheck {
	if in == nil {
		return nil
	}
	out := new(EndpointCheck)
	in.DeepCopyInto(out)
	return out
}
func (in *EndpointCheck) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *EndpointCheckList) DeepCopyInto(out *EndpointCheckList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		out.Items = make([]EndpointCheck, len(in.Items))
		for i := range in.Items {
			in.Items[i].DeepCopyInto(&out.Items[i])
		}
	}
}
func (in *EndpointCheckList) DeepCopy() *EndpointCheckList {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckList)
	in.DeepCopyInto(out)
	return out
}
func (in *EndpointCheckList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}
func (in *EndpointCheckParameters) DeepCopyInto(out *EndpointCheckParameters) {
	*out = *in
	if in.EndpointIDRef != nil {
		out.EndpointIDRef = in.EndpointIDRef.DeepCopy()
	}
}
func (in *EndpointCheckParameters) DeepCopy() *EndpointCheckParameters {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckParameters)
	in.DeepCopyInto(out)
	return out
}
func (in *EndpointCheckObservation) DeepCopyInto(out *EndpointCheckObservation) {
	*out = *in
	in.LastCheckedAt.DeepCopyInto(&out.LastCheckedAt)
}
func (in *EndpointCheckObservation) DeepCopy() *EndpointCheckObservation {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckObservation)
	in.DeepCopyInto(out)
	return out
}
func (in *EndpointCheckSpec) DeepCopyInto(out *EndpointCheckSpec) {
	*out = *in
	in.ManagedResourceSpec.DeepCopyInto(&out.ManagedResourceSpec)
	in.ForProvider.DeepCopyInto(&out.ForProvider)
}
func (in *EndpointCheckSpec) DeepCopy() *EndpointCheckSpec {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckSpec)
	in.DeepCopyInto(out)
	return out
}
func (in *EndpointCheckStatus) DeepCopyInto(out *EndpointCheckStatus) {
	*out = *in
	in.ManagedResourceStatus.DeepCopyInto(&out.ManagedResourceStatus)
	in.AtProvider.DeepCopyInto(&out.AtProvider)
}
func (in *EndpointCheckStatus) DeepCopy() *EndpointCheckStatus {
	if in == nil {
		return nil
	}
	out := new(EndpointCheckStatus)
	in.DeepCopyInto(out)
	return out
}
