// SPDX-FileCopyrightText: 2026 The provider-runpod Authors
// SPDX-License-Identifier: Apache-2.0

// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import xpv2 "github.com/crossplane/crossplane/apis/v2/core/v2"

func (mg *EndpointCheck) GetCondition(ct xpv2.ConditionType) xpv2.Condition {
	return mg.Status.GetCondition(ct)
}
func (mg *EndpointCheck) GetManagementPolicies() xpv2.ManagementPolicies {
	return mg.Spec.ManagementPolicies
}
func (mg *EndpointCheck) GetProviderConfigReference() *xpv2.ProviderConfigReference {
	return mg.Spec.ProviderConfigReference
}
func (mg *EndpointCheck) GetWriteConnectionSecretToReference() *xpv2.LocalSecretReference {
	return mg.Spec.WriteConnectionSecretToReference
}
func (mg *EndpointCheck) SetConditions(c ...xpv2.Condition) { mg.Status.SetConditions(c...) }
func (mg *EndpointCheck) SetManagementPolicies(p xpv2.ManagementPolicies) {
	mg.Spec.ManagementPolicies = p
}
func (mg *EndpointCheck) SetProviderConfigReference(r *xpv2.ProviderConfigReference) {
	mg.Spec.ProviderConfigReference = r
}
func (mg *EndpointCheck) SetWriteConnectionSecretToReference(r *xpv2.LocalSecretReference) {
	mg.Spec.WriteConnectionSecretToReference = r
}
